export const PATH = {
  HOME: "/",
  TICKET: "/booking",
  MOVIE_DETAILS: "/movie-details",
  BOOKING_TICKETS_MOVIE: "/booking-tickets-movie",
  LOGIN: "/auth/login",
  REGISTER: "/auth/register",
  ADMIN: "/admin",
  DASHBOARD: "/admin/dashboard",
  MOVIE_MANAGEMENT: "/admin/movie-management",
  USER_MANAGEMENT: "/admin/user-management",
  SHOWTIME_MANAGEMENT: "/admin/films/showtime",
  NOT_FOUND: "*",
  MOVIES: "/movies",
  COMING_SOON: "/coming-soon",
};
